services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cookiecms-frontend:latest
    container_name: cookiecms-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - frontend-logs:/app/.next/logs
    networks:
      - cookiecms-network

networks:
  cookiecms-network:
    driver: bridge

volumes:
  frontend-logs: